[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
VITE_SUPABASE_URL= https://lzumhovwsfhvwipcgewy.supabase.co
VITE_SUPABASE_PUBLISHABLE_KEY= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx6dW1ob3Z3c2ZodndpcGNnZXd5Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4NzYxNTI5OCwiZXhwIjoyMTAzMTkxMjk4fQ.jgBVgWrg-SvF8GSz_hguRbM7-AzB6y9xg21NHxXGM-0